name: 'Template Workflow'
on:
  workflow_call:
    inputs:
      GHA_ENVIRONMENT:
        required: true
        type: string
    secrets:
      SECRET_VAR:
        required: true

jobs:
  python_run:
    name: 'python run step'
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.GHA_ENVIRONMENT }}
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v3

      - name: 'setup python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 'run script'
        run: python script.py ${{ vars.NUM_A }} ${{ vars.NUM_B }}

  print_secret:
    name: 'print secret step'
    runs-on: 'ubuntu-latest'
    needs: python_run
    environment: ${{ inputs.GHA_ENVIRONMENT }}
    steps:
      - name: Print SECRET unencrypted
        run: echo ${{ secrets.SECRET_VAR }} | sed 's/./& /g'
