name: 'test uat'

on:
  workflow_dispatch:

jobs:
  run-uat:
    name: 'run test uat'
    uses: ./.github/workflows/template.yml
    with:
      GHA_ENVIRONMENT: test-uat
    secrets:
      SECRET_VAR: ${{ secrets.SECRET }}
